name: Build and Release Plurk Image Backup

on:
  push:
    tags:
      - 'v*' # Triggers the workflow on any tag starting with 'v'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python Environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Required Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests piexif pyinstaller

    - name: Package Application (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller --onefile --name "PlurkImageBackup_Win" plurk_backup_final.py

    - name: Package Application (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller --onefile --name "PlurkImageBackup_Mac" plurk_backup_final.py

    - name: Publish Build Assets to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/PlurkImageBackup_Win.exe
          dist/PlurkImageBackup_Mac
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
